### ISSUE TITLE
[bug] If you add a new song after the previous has ended, you can't hear song

### ISSUE THREAD

**Issue by DoNotSpamPls** [dabbotorg/java-music-bot#119]
How to reproduce::
1. add a song to dabBot
2. listen until the end
3. add a new song after the previous one has ended
4. you can't hear the song, nowplaying counter stays at 00:00

**Comment by ducc** [comment]
(hopefully) fixed by https://github.com/dabbotorg/java-music-bot/commit/92f4fbb4e9c8a1a75b2390677243d29c0023789b will close once confirmed

**Comment by ducc** [comment]
solved
