### ISSUE TITLE
Twitch streams don't work anymore

### ISSUE THREAD

**Issue by DoNotSpamPls** [dabbotorg/java-music-bot#136]
~~Twitch.TV has banned all OVH links from its service, presumably to stop restreaming.~~

Apparently I was a total maroon, Twitch just changed their URLs from twitch.tv to go.twitch.tv 😃

**Comment by tombowditch** [comment]
Is there any evidence for this other than “twitch tv doesn’t work”?

**Comment by DoNotSpamPls** [comment]
*shrug*

Maybe I'm incorrect, but the fact stands - Twitch.TV doesn't work anymore 😦

**Comment by ducc** [comment]
It's not OVH. https://github.com/sedmelluq/lavaplayer/pull/65. sedmelluq is on holiday atm so it will be merged when he gets back :)

**Comment by DoNotSpamPls** [comment]
Ah, thanks for the headsup!

**Comment by DoNotSpamPls** [comment]
The PR you referrenced was fixed, but the issue still remains. 🤔
